### ISSUE TITLE
Any C/C++ implementation

### ISSUE THREAD

**Issue by cyberpunkoff** [jvdsn/crypto-attacks#1]
Hey, first of all - sorry for writing in issues section and disturbing anyone but I have a question that haunts me. Your python implementation is great, but I wondering is there anython like that but on c/c++? Especially I'm searching for branch and prune algo for known random bits for p and q. It was very hard to find even your code, it's just algo description everywhere and not code. So, if you know anything about it, I would really appreciate.

**Comment by jvdsn** [comment]
I'm sorry, I don't know of any implementation in C or C++. However, it shouldn't be too hard to implement yourself, especially the easier parts (with p and q bits known). Alternatively, if you're concerned about speed, you could try running the algorithm with PyPy. Note that some parts of that code depend on SageMath, so you'd need to remove or replace that if you want to use PyPy.
