### ISSUE TITLE
shared.ecc.generate_with_order speed up

### ISSUE THREAD

**Issue by uvicorn** [jvdsn/crypto-attacks#19]
same problem: https://github.com/J08nY/ecgen/issues/23
`pari.qfbsolve(pari.Qfb(1, 0, -D), 4 * m, 1)` is slow because pari try to factor m every time.
our solution:
```
m = Integer(sys.argv[1])
out = subprocess.check_output(['./yafu'], input=f'factor({m})'.encode())
for p in [int(a.split(b' = ')[1]) for a in out.splitlines() if b' = ' in a and a[0] == b'P'[0]]:
    if p > 1000:
        pari.addprimes(p)
```
seems we can replace yafu with default sage `factor(m)`

**Comment by jvdsn** [comment]
Does a23ab9acf6d71637509cd304b28c0ede8d649933 address your concerns?

**Comment by uvicorn** [comment]
Yes, thanks! Btw for me almost always worked D=[16,64,256] and idk why
