### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by hellboyboyhell** [jvdsn/crypto-attacks#2]
hi i want to practice with your code , can u explain to me how can i use smart's attack on y^2=x^3+7 module P=61 while  t=1 , for points Q=(30,44) and G=(9,2) ??

**Comment by hellboyboyhell** [comment]
how is sage.all configuration?

**Comment by jvdsn** [comment]
Hi, if you want to use this, you will need to make sure sage is on your python path. Alternatively, you can try running `sage -python <file.py>`.

**Comment by hellboyboyhell** [comment]
I tried several ways but felt in error every time
can u explain more or give me a tutorial link please? its important to me

**Comment by jvdsn** [comment]
If you want to run Smart's attack, you can go to the `ecc` directory, and then do: `sage -python smart_attack.py`. Of course, you need to have some code in this file to call the `attack` method. If this does not work, please post the errors you get.

**Comment by hellboyboyhell** [comment]
I call smart_attack.py but nothing happens and no input requested for curve configuration!
where must i apply this configs:

E = EllipticCurve(GF(61),[0,7])
P = E(9,2)
Q = E(30,44)
Q = n*P

theese are elements definition of my curve in sage language , but i dont know how i should to apply to work with your code

**Comment by jvdsn** [comment]
You need to program a method yourself to call the attack, it does not prompt for curve configuration. It shouldn't be too hard if you have sage experience.

**Comment by hellboyboyhell** [comment]
ok I got it , unfortunatly I am begginer in sage and I think I cant run code correctly until next months:)))
