### ISSUE TITLE
memory usage in hencel lift

### ISSUE THREAD

**Issue by uvicorn** [jvdsn/crypto-attacks#20]
https://github.com/jvdsn/crypto-attacks/blob/master/shared/hensel.py#L33
FIX:
```python
#        roots = list(range(p))
        roots = range(p)
```
because `list(range(big_p))` will use so much memory

**Comment by uvicorn** [comment]
https://github.com/jvdsn/crypto-attacks/blob/master/shared/hensel.py#L43
same problem. seems need rewrite when polynomial `f`=0

**Comment by jvdsn** [comment]
Why are you using `hensel_roots` for `f=0`?

**Comment by jvdsn** [comment]
Please verify if #29f989e addresses this issue
