### ISSUE TITLE
Please implement Addleman’s algorithm for solving discrete logarithms : the first index calculus algorithm.

### ISSUE THREAD

**Issue by ytrezq** [jvdsn/crypto-attacks#23]
As far I understand, 1 distinctive feature of [such algorithm](https://pages.cs.wisc.edu/~cs812-1/adleman.pdf) is it fully works in subgroups/suborders.

All other index calculus algorithms can do this only for the linear algebra phase and thus their complexity is determined by the field size. Thus when the discrete logarithm only lies under a large prime factor, this makes a situation making Pollard’s rho faster than modern index calculus methods if the field is too large.

**Of course, the factorization part of Adleman can be done using more modern methods**…

**Comment by jvdsn** [comment]
I don't think this is a good fit for the project, this seems like a more general-purpose algorithm.

**Comment by ytrezq** [comment]
@jvdn but you do implement Pollard rho? Why not a faster sutff?

**Comment by jvdsn** [comment]
I do not implement Pollard's rho algorithm. In fact a version of it was removed 4 years ago from this repository because Sage has a built-in algorithm.
