### ISSUE TITLE
Extended partial key exposure attacks on RSA: Improvement up to full size decryption exponents

### ISSUE THREAD

**Issue by skintigh** [jvdsn/crypto-attacks#6]
Could you please add support for the attack in the 2020 paper:

"Extended partial key exposure attacks on RSA: Improvement up to full size decryption exponents"
Kaichi Suzuki, Atsushi Takayasu, Noboru Kunihiro 

Thank you

**Comment by jvdsn** [comment]
Is there any specific case or challenge for which the existing methods are insufficient?

**Comment by skintigh** [comment]
I thought they had significantly better results for one, but realize I misinterpreted their results.

Thank you for your amazing repo!

**Comment by jvdsn** [comment]
If I understand correctly, their attack is somewhat better, but it also looks significantly more complex. When I looked at that paper, I didn't think the implementation effort would be worth the results, but I would be open to revisit this if it is actually needed.
